### ISSUE TITLE
No module named 'utilities.file'

### ISSUE THREAD

**Issue by lisimeng1996** [thadikari/decoders#1]
run main.py , show“No module named 'utilities.file'”

**Comment by thadikari** [comment]
Hi lisimeng1996, 
You will need to initialize the utilities sub-module (this is another git repository) by executing `git submodule update --init --recursive` as described in https://stackoverflow.com/questions/10168449/git-update-submodules-recursively .

**Comment by lisimeng1996** [comment]
hi，i have git clone your code .I change my python interpreter  to 32-bit and find some new promblems :
/*
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/decoders/src/main.py", line 7, in <module>
    from models import models
  File "C:\Users\Administrator\Desktop\decoders\src\models.py", line 1, in <module>
    import bsc, bec, biawgn
  File "C:\Users\Administrator\Desktop\decoders\src\bsc.py", line 8, in <module>
    import admm
  File "C:\Users\Administrator\Desktop\decoders\src\admm.py", line 6, in <module>
    from parity_polytope import exact
  File "C:\Users\Administrator\Desktop\decoders\src\parity_polytope\exact.py", line 9, in <module>
    lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python3.6\Python36-32\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python3.6\Python36-32\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module was not found。

Caught OSError! Make sure a Python-32bit version is running.
https://stackoverflow.com/questions/19849077/error-loading-dll-in-python-not-a-valid-win32-application.
*/

**Comment by thadikari** [comment]
I have fixed this error. Update your code by running `git pull' and check if this works. Are you trying to run the admm decoder?
